baseURL = "https://censored-state.com/"
languageCode = "en-us"
title = "Censored State"
theme = "PaperMod"

[params]
  author = "Merecat"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowSearch = true
  assets = { customCSS = ["css/custom.css"] }

[menu]

  [[menu.main]]
    name = "Resources and Tools"
    url = "/circumvention-tools"
    weight = 1

  [[menu.main]]
    identifier = "censored-lab"
    name = "Censored Lab"
    url = "/censored-lab"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 3

[taxonomies]
  tag = "tags"
  category = "categories"

  [[menu.main]]
    name = "Censorship Map"
    url = "/map/"
    weight = 4

  [markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


